services:
  - type: web
    name: tether-bot
    env: python
    buildCommand: |
      pyenv install 3.10.13 -s
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
